---
# defaults file for gitlab
gitlab_domain: "gitlab.epogodin.ru"
gitlab_external_url: "http://{{ gitlab_domain }}/"
gitlab_edition: "gitlab-ce"
gitlab_config_template: "gitlab.rb.j2"
gitlab_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"

# Dependencies.
gitlab_dependencies:
  - postfix
  - curl
  - tzdata

# GitLab root password after install
gitlab_root_pass: "password"
